### ISSUE TITLE
could you give some example commands on running euroc dataset?

### ISSUE THREAD

**Issue by fzheng010** [KumarRobotics/msckf_vio#10]
I can run the following:
roslaunch msckf_vio msckf_vio_euroc.launch
rosbag play MH_04_difficult.bag

But how to show visualization? It looks like there is no rviz.launch built.

**Comment by fzheng010** [comment]
@kartikmohta @ke-sun Thanks in advance!

**Comment by pxlong** [comment]
just run `rviz`, and load the "rviz_euroc_config.rviz" config file into the rviz.

**Comment by fzheng010** [comment]
Cool. Thanks! @pxlong
