### ISSUE TITLE
The Groundtruth

### ISSUE THREAD

**Issue by jingshaojing** [KumarRobotics/msckf_vio#100]
For fast flight dataset , how can I get the position and velocity of gps?  It is workable for  using  rosbag play?  And i have see the matlab script for dataset, it only use 2*N velocity? what is about  position?

**Comment by ke-sun** [comment]
The GPS data are in the rosbag files.
The matlab script is to compute the time and yaw offset between GPS and the odometry.
Once we have the offset, we could transform either the odometry data or the GPS data for proper comparison.

**Comment by jingshaojing** [comment]
thanks，  I have understand this meaning , I will try

**Comment by jingshaojing** [comment]
I have a new question,for  V1_01_easy.bag，the groundtruth in mav0 has 28713 raws in data.csv, and I save pose data  in txt file only has 2893 raws, My question is whether too little Pose data is being saved？ @ @ke-sun

**Comment by jingshaojing** [comment]
Apologize for my disturbance, can i directly use matlab script with flight dataset, I found .m file is only a  function, so  I need to read rosbag file and store relative information in .mat file, and write a main function in matlab to use the function you give ? I do not know my understanding is right?

**Comment by ke-sun** [comment]
There seems to be rosbag support in matlab. 
https://www.mathworks.com/help/ros/ref/rosbag.html

**Comment by jingshaojing** [comment]
Thanks @ke-sun
