### ISSUE TITLE
Question about the observability constrain of measurement Jacobian

### ISSUE THREAD

**Issue by brick-ai** [KumarRobotics/msckf_vio#108]
In paper _**Observability-constrained Vision-aided Inertial Navigation**_, the measurement Jacobian is modified with Imu state rather than camera state. See the difference below:

![1](https://user-images.githubusercontent.com/26831819/110577331-66d4c200-819d-11eb-8593-76bf56ccdf14.png)

![2](https://user-images.githubusercontent.com/26831819/110577344-6b997600-819d-11eb-8030-891293875cc3.png)

Which one should we use to modify the measurement Jacobian? Why?

**Comment by ke-sun** [comment]
> In paper _**Observability-constrained Vision-aided Inertial Navigation**_, the measurement Jacobian is modified with Imu state rather than camera state.

I am not 100% sure I understand the question (I probably become rusty on this).
May I ask how the referenced paper section is related to the question?

**Comment by brick-ai** [comment]
@ke-sun 

Sorry, I didn't make this question clearer.

To satisfy the observability constrain,  the state transition matrix and the measurement Jacobian need to be modified according to following method:
![image](https://user-images.githubusercontent.com/26831819/110654177-df1ca100-81f8-11eb-992d-a9336832b624.png)
![image](https://user-images.githubusercontent.com/26831819/110654026-bdbbb500-81f8-11eb-9efa-6a9861be3c07.png)

When modifying the measurement Jacobian, the equation (25) is simplified to 
![image](https://user-images.githubusercontent.com/26831819/110655535-193a7280-81fa-11eb-8a87-592d2f4a8e66.png)
And then modified according to
![image](https://user-images.githubusercontent.com/26831819/110655786-4edf5b80-81fa-11eb-989a-313a568d1d62.png)
Just like what the code does:
![1](https://user-images.githubusercontent.com/26831819/110656529-fceb0580-81fa-11eb-8f88-47380d95c84e.PNG)

But the difference is that the paper modifies **H** with **_IMU states_** while the code with **_camera states_**.

To satisfy the observability constrain, should we modify the measurement Jacobian **H** with **_IMU states_** or **_camera states_**?

**Comment by ke-sun** [comment]
I see what you meant.

The original work on observability constraint (http://seanbow.com/papers/tr_2012_1.pdf) does not exactly use an *multi-state* extended Kalman filter, but an extended Kalman filter with just IMU state in the state vector. As in the footnote on page 5, the work assumes the IMU frame is coincident with the CAM frame for simplicity. Therefore, the IMU state shows up in the measurement model, so as in the computation of observability constraints.

If we include the CAM states in the state vector (as in the original MSCKF), only CAM states show up in the measurement model. Therefore, their estimates should be used in enfocing the observability constraints.

**Comment by brick-ai** [comment]
Oh, I see. Thanks!

Does that mean we have different right nullspace **N** of the observability matrix from EKF-SLAM?

Do you have any materials or references so I can deduce the formulations for MSCKF?

**Comment by ke-sun** [comment]
I am not sure if there is a specific reference for that. But if you replace the IMU state with the CAM state in the measurement model, I think the observability analysis from the paper should translate.
