### ISSUE TITLE
compare with OKVIS

### ISSUE THREAD

**Issue by zz1120122573** [KumarRobotics/msckf_vio#11]
Hi, I want to compare this vio with OKVIS, but I cannot run Euroc V203 dataset. Do I need to modify some parameters? I find the compare result in your paper. Thanks!

**Comment by ke-sun** [comment]
As mentioned in the paper, it does not run on V2_03 since the image intensity is different for the stereo images.

**Comment by zz1120122573** [comment]
Thanks for your reply, could you tell me how to run OKVIS on V2_03? I want to know why I cannot run it but you can. Thanks.
