### ISSUE TITLE
The Coordinate frame

### ISSUE THREAD

**Issue by jingshaojing** [KumarRobotics/msckf_vio#111]
I want to transform the quaternion of VIO to Euler angle, so the order of rotation is ZYX(yaw,pitch ,roll) or other?

**Comment by ke-sun** [comment]
Hi @jingshaojing 

Thank you for being interested in our repository.

But, I notice that your questions (this one and #110) are not tightly related to this repository. It might be inefficient and inappropriate to discuss them through issues. You may consider to resort to other references.

**Comment by jingshaojing** [comment]
ok，I am sorry&nbsp; for my disturbance，thanks



---Original---
From: "Ke ***@***.***&gt;
Date: Sun, Mar 28, 2021 01:48 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KumarRobotics/msckf_vio] The Coordinate frame (#111)




 
Hi @jingshaojing
 
Thank you for being interested in our repository.
 
But, I notice that your questions (this one and #110) are not tightly related to this repository. It might be inefficient and inappropriate to discuss them through issues. You may consider to resort to other references.
