### ISSUE TITLE
hi, about the coordinator of left camera

### ISSUE THREAD

**Issue by ynma-hanvo** [KumarRobotics/msckf_vio#118]
hello , everyone,   I am  not sure how do i  get the cam0   coordinator( orientation and position)   with respect  to world;
as the IMUState only got the coordinator for imu: 
//================================================
// Orientation
  // Take a vector from the world frame to
  // the IMU (body) frame.
  Eigen::Vector4d orientation;

  // Position of the IMU (body) frame
  // in the world frame.
  Eigen::Vector3d position;
//===================================
suppose I have a fixed transformation for cam_to_imu   as   T_cam_imu  (kalibr result);
how i can do it with eigen ？  thanks for you answer;

**Comment by ke-sun** [comment]
You could simply multiply the two frames,
T_world_lcam = T_world_imu * T_imu_lcam
T_world_imu is estimated by the software.
T_imu_lcam is in the calibration file.
