### ISSUE TITLE
hi, no ground truth shown with the euroc dataset.

### ISSUE THREAD

**Issue by ynma-hanvo** [KumarRobotics/msckf_vio#119]
hello, 
I ran the euroc launch file and open the corresponding rviz file, but i can not see any ground truth stuff for a comparison. 
i checked the bag file, there is a TransformStamped message but it is not shown in rivz. 
thanks a lot/

**Comment by ke-sun** [comment]
If I remember correctly,  there's ground truth data in the euroc bags already.
If they are not shown in the rviz, maybe you could try add a new display for that.
