### ISSUE TITLE
how to show euroc ground-truth in rviz?

### ISSUE THREAD

**Issue by fzheng010** [KumarRobotics/msckf_vio#12]
I see in the posted video that groundtruth was shown as well. However, I cannot show it locally. 

I did the following when I ran an euroc sequence:

- roslaunch msckf_vio  msckf_vio_euroc.launch
- rviz (load rviz_euroc_config.rviz manually)
- rosbag play V1_03_difficult.bag

Am I missing some step?

Thanks in advance! @kartikmohta @ke-sun

**Comment by ke-sun** [comment]
Unfortunately, the code in the repo does not process the ground truth odometry.

**Comment by fzheng010** [comment]
Got it. Would be great if you could share that code as well. Anyway, thanks! Awesome work.
