### ISSUE TITLE
'unroll' in alignGPSandOdomVelocity.m

### ISSUE THREAD

**Issue by impce-lg** [KumarRobotics/msckf_vio#122]
'unroll' may be an undefined function in alignGPSandOdomVelocity.m:
unroll(yaw+epsilon)

which can not be identified by the program.

Could anyone tell me the how to fix this?

**Comment by ke-sun** [comment]
Apologies for the late reply. I wrote the script many years ago. Based on another read, the purpose of `unroll` is to convert the agent to [-pi, pi] or [0, 2pi].
