### ISSUE TITLE
How hard is to do loop closure in this repo?

### ISSUE THREAD

**Issue by brunopinto900** [KumarRobotics/msckf_vio#126]
Hello,

How hard is to perform loop closure & non-linear optimization with this repo? I am trying to use this filter-based VIO into a full Visual SLAM. How feasible is this?

Thank you.

**Comment by versatran01** [comment]
It is difficult if you are trying to modify it into a full-fledged slam system. However you can always just use the output of vio to build your slam graph.

**Comment by brunopinto900** [comment]
Thanks for your input.
