### ISSUE TITLE
How can I adapt the webcam?

### ISSUE THREAD

**Issue by Polibo1** [KumarRobotics/msckf_vio#128]
Thanks for this project.

I don't have a stereo camera now. So, I want to use the webcam. 

How can I adapt the webcam to this project?

**Comment by fcladera** [comment]
Hi! This project relies on a calibrated stereo system to perform VIO with global shutter sensors (or rolling-shutter compensated sensors). You may check our papers [1](https://ieeexplore.ieee.org/abstract/document/8463214) [2](https://arxiv.org/pdf/1712.00036.pdf) [3](https://arxiv.org/abs/2109.06479) where we describe systems using MSCKF.

While it is possible to adapt MSCKF to a monocular sensor, this repo does not implement this feature.
