### ISSUE TITLE
trajectory

### ISSUE THREAD

**Issue by jixiedaima** [KumarRobotics/msckf_vio#13]
I can't show the trajectory information in rviz and I don't know why?
platform: ubuntu16.04.2 kinetic opencv3.3.1

**Comment by ke-sun** [comment]
The software does not publish the trajectory as `nav_msgs/Path`.

**Comment by jixiedaima** [comment]
How can I get the trajectory information?

**Comment by kartikmohta** [comment]
You can write a simple node to accumulate the output odometry messages into a `nav_msgs/Path` message for visualization.

**Comment by jessicajie** [comment]
Can you solve it ? Can you explain it in detail？thanks a lot .

**Comment by SouthEastleo** [comment]
I meet the same question now,and i'm trying to write a node to subcribe the odom message.So,we can talk about it.thanks.

**Comment by kartikmohta** [comment]
A simple node to take `nav_msgs/Odometry` messages and populate a `nav_msgs/Path` from it: https://gist.github.com/kartikmohta/67cafc968ba5146bc6dcaf721e61b914

You can remap the topics to match whatever your input and output topic names are.

**Comment by SouthEastleo** [comment]
Thanks a lot，I have solved it.Best wishes for you

**Comment by TurtleZhong** [comment]
![figure_1-1](https://user-images.githubusercontent.com/19700579/35810022-50a85bc4-0ac5-11e8-8075-f5d437c91174.png)

**Comment by TurtleZhong** [comment]
Hello, I save the trajectory and plot the trajectory. But I found that the translation is really strange. Below are the trajectory of MH_01_easy.bag.
![figure_1-1](https://user-images.githubusercontent.com/19700579/35810086-84590180-0ac5-11e8-9f82-7946fe5a8c2f.png)
I only add these in your code:

```
  Vector3d t_b_w =  T_b_w.translation();
  outFile << t_b_w(0) / 1000. << " " << t_b_w(1) / 1000. << " " << t_b_w(2) / 1000. << endl;
```
and the plot the trajectory using this:
```
import numpy as np
import matplotlib.pyplot as plt


trajectory_path = 'trajectory.txt'
trajectory_data = np.loadtxt(trajectory_path, dtype=np.float64, delimiter=' ')
gt_path = '../gt_path/mh_01_easy.csv'
gt_data = np.loadtxt(gt_path, dtype=np.float64, comments='#', delimiter=',')
gt_data = gt_data[:, 1:4]

ax = plt.subplot(1, 2, 1, projection='3d')
ax.plot(gt_data[:, 0], gt_data[:, 1], gt_data[:, 2],
            '-', alpha=0.5, color="red", )

ax = plt.subplot(1, 2, 2, projection='3d')
ax.plot(trajectory_data[:, 0], trajectory_data[:, 1], trajectory_data[:, 2],
            '-', alpha=0.5, color="blue", )

plt.show()
```
I didn't know why the translation is so strange.
Can anyone help me?
@jixiedaima @ke-sun @kartikmohta @jessicajie @SouthEastleo 
Thank you!

**Comment by ke-sun** [comment]
The software does not run on EuRoC `MH_01_easy.bag` and `MH_02_easy.bag`. As explained in the README, the algorithm requires the sensor to start from staic in order to initialize the orientation and IMU bias. unfortunately, `MH_01_easy.bag` and `MH_02_easy.bag`  do not have the initial static period.

**Comment by jixiedaima** [comment]
Can it get good performance in other EuRoC ?

**Comment by ke-sun** [comment]
The rest should be fine.

**Comment by TurtleZhong** [comment]
@ke-sun Really thank you！！！

**Comment by jixiedaima** [comment]
thanks

**Comment by chutsu** [comment]
@TurtleZhong can you quickly comment why you divided the translations by 1000 in your code snippet?

    Vector3d t_b_w =  T_b_w.translation();
    outFile << t_b_w(0) / 1000. << " " << t_b_w(1) / 1000. << " " << t_b_w(2) / 1000. << endl;

**Comment by SongBiaoVision** [comment]
I want to know how long is the initial static period?Thank you.

**Comment by ke-sun** [comment]
@alexSongB 
It depends on the IMU rate. The software currently needs 200 IMU msgs to estimate the initial orientation. But you can change it to other reasonable numbers. See
https://github.com/KumarRobotics/msckf_vio/blob/1e524eb957b9ea32350dfdc9c88abf56563e4680/src/msckf_vio.cpp#L239

**Comment by SongBiaoVision** [comment]
Thank you.

**Comment by SongBiaoVision** [comment]
I get something confused. Can you quickly comment why you divided the translations by 1000 in your code snippet? what‘s the unit for the t_b_w(0) ? @ke-sun

**Comment by SongBiaoVision** [comment]
I want to know how can you get the error between groundtruth and trajectory?where is the groundtruth? I am looking forward for your reply, thank you.

**Comment by ke-sun** [comment]
There is ground truth in the EuRoC dataset. You may want to compare with that. Regarding #19 , the path messages are only for debugging purpose, they are not included in the current version.

**Comment by SongBiaoVision** [comment]
Is the ground truth included in data.csv .but I found that the rows of trajectory is more less than the row of the data.csv. So I can't compare the trajectory and ground true by different sharp. @ke-sun

**Comment by yuyadanyadan** [comment]
Did someone write the node???  Tank you very much !

**Comment by chenwinki** [comment]
I know a tool named EVO used for compare trajectory

**Comment by bobododosjl** [comment]
> 
> 
> Thanks a lot，I have solved it.Best wishes for you

can u show me the detail of the change?thank u

**Comment by bobododosjl** [comment]
> A simple node to take `nav_msgs/Odometry` messages and populate a `nav_msgs/Path` from it: https://gist.github.com/kartikmohta/67cafc968ba5146bc6dcaf721e61b914
> 
> You can remap the topics to match whatever your input and output topic names are.

     

can u show me the detail of the change?thank u
