### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Polibo1** [KumarRobotics/msckf_vio#130]
I used the ZED stereo camera.

I modified the topic in the launch files.

/zed/zed_node/left/image_rect_color
/zed/zed_node/right/image_rect_color
(in image_processor_euroc.launch)

but, I have a problem with the picture.

What should I modify???
.
.
.
.
And I don't know what is **child_frame_id** in msckf_vio_euroc.launch.
.
.
.
.

![Screenshot from 2022-03-30 20-34-04](https://user-images.githubusercontent.com/72862584/160826450-82ac967b-2bed-4a29-8ee8-b5339a6fee0d.png)

**Comment by versatran01** [comment]
See #128. Zed is rolling-shutter so it is not supported.

**Comment by Polibo1** [comment]
Thanks! I solved that problem.

But, I don't know what is child_frame_id in msckf_vio_euroc.launch.

I modified the child_frame_id to /zed/zed_node/odom

but result is not good
