### ISSUE TITLE
Where can I find the IMU state in msckf_vio.cpp?

### ISSUE THREAD

**Issue by Polibo1** [KumarRobotics/msckf_vio#131]
I want to compare msckf_vio.cpp with the paper "Robust Stereo Visual Inertial Odometry for Fast Autonomous Flight".

What represents the IMU state in msckf_vio.cpp that is same in the paper?

And I want to know what is child_frame_id in msckf_vio_euroc.launch.

I changed that to /zed/zed_node/odom. But the result is not good.

**Comment by versatran01** [comment]
Child frame id is the child frame id of a transform. you can set it to whatever name you want. It does not affect the odometry result, so I don't quite understand what you meant by "the result is not good"?
https://docs.ros.org/en/lunar/api/geometry_msgs/html/msg/TransformStamped.html

IMU state is at https://github.com/KumarRobotics/msckf_vio/blob/master/include/msckf_vio/imu_state.h

**Comment by Polibo1** [comment]
Thanks for your reply.

I used ZED camera and 3DMGX5-AHRS IMU of microstrain.

My rostopic list :
![1](https://user-images.githubusercontent.com/72862584/161483251-4822a1ac-e948-4fbc-8488-af755ba50852.jpg)
![2](https://user-images.githubusercontent.com/72862584/161483256-6cb426c8-8254-4b00-980d-4722ff780c1f.jpg)
![3](https://user-images.githubusercontent.com/72862584/161483260-cd79125c-49eb-4fd4-bdbc-7a5822639c2e.jpg)






"the result is not good" is seen this video.

https://user-images.githubusercontent.com/72862584/161484525-30255262-d5e5-4440-8b80-1bc52d81778d.mp4






I modified 'child_frame_id' to `/zed/zed_node/odom` in msckf_vio_euroc.launch.

But, the  `/zed/zed_node/odom`  flied away, when I moved the ZED camera.

Is it wrong?

That is my important problem.

**Comment by versatran01** [comment]
It is not wrong, it's just that the filter did not converge.
You are using hardware that is not supported, there is no guarantee that it will work.

**Comment by Polibo1** [comment]
the ZED camera that I am using does not have IMU inside so I used an external IMU (3DMGX5-AHRS ) to use the topic in the package. Will it work if I use a static transformation between the base link of the ZED camera and the base link of IMU?

**Comment by versatran01** [comment]
You need to specify the transform in the calibration file.
https://github.com/KumarRobotics/msckf_vio/blob/master/config/camchain-imucam-euroc.yaml
