### ISSUE TITLE
about the covariance divergence

### ISSUE THREAD

**Issue by Polibo1** [KumarRobotics/msckf_vio#137]
Thanks for your project.

I have two question2.

First,

When I did the VIO, the purple ellipsoid is bigger and bigger.

I think when there aren't the feature points, the purple ellipsoid is bigger and bigger.

It is the position covariance??? 

I want to know the related equation in the paper.

I want to know why the purple ellipsoid is bigger and bigger.

---------------------------------------------------------------------------

Second,

I did five laps at the same route.

![그림1](https://user-images.githubusercontent.com/72862584/171994147-42176d6d-c6ee-49c8-804c-3d60d78563c1.png)
.
.
.
.
However, the estimated position came out as shown in the picture above.

The height must be constant, but the test results show that it goes up or down.

Can you tell me why?

**Comment by versatran01** [comment]
In vio XYZ and yaw are not observable so their covariance will grow.
The covariance is simply extracted from the filter's full covariance matrix.

This could be caused by many things, for example, inaccurate intrinsic/extrinsic calibration, wrong gravity norm, etc. It's hard to tell what exactly causes this.

**Comment by Polibo1** [comment]
Is the z-axis of the path getting smaller because the covariance also increases?

**Comment by versatran01** [comment]
I don't understand your question

**Comment by Polibo1** [comment]
I'm talking about the figure above.

I experimented on the track (first figure).

But, the trajectory result is the second figure.

Is this result also due to increased covariance?

and Can you tell me the equation about covariance that you said?
.
.
![image01](https://user-images.githubusercontent.com/72862584/172041767-869b4a9b-1ffa-4439-9e24-9c0e32c2a1a0.png)
.
.
.
![front_3차원_2](https://user-images.githubusercontent.com/72862584/172041894-a994e8e3-5407-4e31-bf93-6c5a096a6c77.png)

**Comment by versatran01** [comment]
Could be, but most likely it's the other way around.

See details at https://en.wikipedia.org/wiki/Kalman_filter#Details
