### ISSUE TITLE
EuRoC ground truth

### ISSUE THREAD

**Issue by mbrossar** [KumarRobotics/msckf_vio#15]
Hello,
I want to compare the filter position estimate with the EuRoC ground truth. But the two trajectories does not match. It seems as a mismatch in the yaw. How did you solve it ? Do you rotate one trajectory by the first difference between estimated yaw  and ground truth yaw ? 
Thanks

**Comment by ke-sun** [comment]
You can transform the ground truth odometry such that the first groud truth frame is at identity.

**Comment by ke-sun** [comment]
Sorry for close this issue by mistake.
