### ISSUE TITLE
Is it possible to share your EuRoc eval script/tool?

### ISSUE THREAD

**Issue by fzheng010** [KumarRobotics/msckf_vio#18]
It would be nice to reproduce the results in Fig. 2.
Thank you in advance!

**Comment by fzheng010** [comment]
@kartikmohta @ke-sun

**Comment by chutsu** [comment]
Curious if this is being worked on? I would be willing to help out if needed.

**Comment by YacongWang** [comment]
@chutsu Do you have any tools or code to plot the Fig 2? Can you share here?

**Comment by chutsu** [comment]
Sry, I didn't have time to recreate the script yet.
