### ISSUE TITLE
msckf run drifting in camera with imu device

### ISSUE THREAD

**Issue by SongBiaoVision** [KumarRobotics/msckf_vio#22]
I use kalibr tools to get the device parameters. when I run msckf algorithm on the device,I get some quesitons. if device stay static,the positing of device is accurate, but if I move the device around, the position of the device drifts bad,I don't know what's wrong.

**Comment by SongBiaoVision** [comment]
Look forward to your soonest reply. Thank you!

**Comment by ke-sun** [comment]
@alexSongB 
Could you be more specific about the problem, such as the reprojection error of Kalibr, the device you are using, are the cameras and imu synchronized, is the image_processor node outputing any matched features? Based on the phenomena, I would check the calibration first.

**Comment by SongBiaoVision** [comment]
![2018-03-26 14-54-46](https://user-images.githubusercontent.com/30278304/37891119-a9426444-3105-11e8-8a93-a47fe10fcd20.png)

**Comment by SongBiaoVision** [comment]
This is the calibration result for the kalibr tool above.Whether the calibration result is good or not. I use the calibration result to run msckf program. If I don't move the camera or move slight, the trajectory seems to be well. But if I move camera severe, the trajectory drifts bad. While the image_processor node outputs matched features.

**Comment by SongBiaoVision** [comment]
![2018-03-26 15-13-40](https://user-images.githubusercontent.com/30278304/37891851-5e01c99a-3108-11e8-803a-b63abb39d080.png)
![2018-03-26 15-13-46](https://user-images.githubusercontent.com/30278304/37891854-61897752-3108-11e8-8dc2-c79a9bdc29a0.png)

**Comment by ke-sun** [comment]
We have also tested our software with MYNT-EYE. Unfortunately, we did not get it to work with the hardware. We would also like to figure out the reason.

**Comment by SongBiaoVision** [comment]
Thank for your reply. I think we can communicate it more for some details. My emil is "songbiao@gdu-tech.com".

**Comment by SongBiaoVision** [comment]
You means msckf didn't work in MYNT-EYE or the result is bad.

**Comment by kartikmohta** [comment]
@alexSongB The result with it is quite bad. The estimate jumps around when you have any significant motion of the camera. We haven't been able to find the exact cause of these jumps yet.

**Comment by pxlong** [comment]
I also have an MYNT_EYE camera. I find that the frame rate of IMU of the camera is not stable (and is not 500 Hz).  Will this lead to bad performance?

**Comment by SongBiaoVision** [comment]
How do you get the frame rate of IMU with the MYNT-EYE camera. Why do you say frame rate of IMU of the camera is not stable? @pxlong

**Comment by pxlong** [comment]
@alexSongB Hi, I use the ROS wrapper of MYNY-EYE camera to get image and imu data. 
So I can check the imu frame rate by "rostopic hz /imu", it is around 470hz.

**Comment by SongBiaoVision** [comment]
Why should the camera rate be 500hz?The EuRoC datasets were collected with a VI sensor on a MAV, which includes synchronized 20Hz stereo images and 200Hz IMU messages. I think the MYNT-EYE is not synchronized.

**Comment by SongBiaoVision** [comment]
I find something strange. If the only wrapper node runs, the rate of IMU is around 500hz. If the msckf node runs besides, the rate of IMU will decreased to around 470hz. Is this the problem bring jumps? @ke-sun @chutsu @pxlong @kartikmohta

**Comment by chutsu** [comment]
I doubt the rate of the IMU alone would make the estimate jump around. In the above discussion you haven't given us your calibration results in terms of errors, so we don't know how good your calibration is. If you have a poor calibration that is more detrimental to the estimate than the rate of IMU. I suggest you share with us the PDF that Kalibr outputted.

Further, Kalibr does not do a IMU intrinsic calibration, so if you read the IMU intrinsics off the manufacturer's specifications you might want to increase each term by a magnitude (i.e. if it says accelerometer noise density was 1e-4, increase it to 1e-3).

These IMU intrinsics are very important to MSCKF as you can imagine. Poor calibration = Poor results.

**Comment by chutsu** [comment]
Btw what does the Falcon (drone mentioned in the paper) use for its IMU? It is not listed in the paper. Judging from an image I found:

![screenshot_2018-03-28_10-50-41](https://user-images.githubusercontent.com/91460/38036963-e20fb6a2-3275-11e8-8077-4084afdd8341.png)

You guys are using a high-end IMU (the red thing between the stereo camera).Could be 1 thing to think about. I assume the cameras are the IDS UI-1221LE, but what focal length?

**Comment by chutsu** [comment]
As side note, I'm also having trouble with drift with a custom setup, in particular I'm using

- IDS uEye 1221LE with 2.1mm focal length
- Invensense MPU 6050 

My camera-imu calibration results looks like this
```
Calibration results
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 1.21224981651, median 1.15408841288, std: 0.589040734197
Gyroscope error (imu0):        mean 0.964409170948, median 0.66739082221, std: 0.993268980175
Accelerometer error (imu0):    mean 1.04925454716, median 0.810603284195, std: 0.886154158242

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 1.21224981651, median 1.15408841288, std: 0.589040734197
Gyroscope error (imu0) [rad/s]:     mean 0.0136388052923, median 0.00943833152172, std: 0.0140469446285
Accelerometer error (imu0) [m/s^2]: mean 4.45161003293, median 3.43909847464, std: 3.75963368682
```

Which is high for accelerometer error, so I'm going to have to calibrate it further.

**Comment by ke-sun** [comment]
I agree that the quality of IMU measurements is very important for the estimation quality. We are using  PointGrey CM3-U3-13Y3M-CS (2.8mm focal length) cameras and VectorNav VN100 IMU.  Here are the typical calibration results from Kalibr for our configuration,
```
Calibration results
===================
Reprojection error squarred (cam0):  mean 0.0258226320892, median 0.0147480323833, std: 0.0503808357645
Reprojection error squarred (cam1):  mean 0.0256774901704, median 0.0129226561016, std: 0.0823128228942
Gyro error squarred (imu0):          mean 0.0937716434596, median 0.0460440702065, std: 0.116936249636
Accelerometer error squarred (imu0): mean 0.170679362745, median 0.109385920057, std: 0.172495253431
```
It seems MYNT-EYE also uses MPU 6050.

**Comment by SongBiaoVision** [comment]
[report-imucam-cameraimucalib.pdf](https://github.com/KumarRobotics/msckf_vio/files/1858282/report-imucam-cameraimucalib.pdf)

**Comment by SongBiaoVision** [comment]
I am sorry I didn't share with you the PDF that Kalibr outputted. The format of my calibrate result is more like chutsu than ke-sun. I can't find  the parameters about "Reprojection error squarred(cam0)" except “Reprojection error(cam0)". I am trying to rule out the impact of IMU rate.

**Comment by SongBiaoVision** [comment]
![2018-03-29 09-32-09](https://user-images.githubusercontent.com/30278304/38065132-23423c30-3334-11e8-9a19-aa0f451dc1c6.png)

**Comment by chutsu** [comment]
I don't actually know how distorted your camera images are, did you ever try with the "equidistant" model by any chance? Your reprojection errors ideally should be less than 0.8 (lower the better).

Take Ke-Sun's reprojection errors for example those numbers are amazing, I've never seen such low reprojection errors in my life...

What was your cam-cam calibration results like?

**Comment by SongBiaoVision** [comment]
![2018-03-29 09-36-59](https://user-images.githubusercontent.com/30278304/38065253-ce6c9416-3334-11e8-8a78-88dcfa15a95a.png)

**Comment by chutsu** [comment]
In the above you're using pinhole-radtan. There's no reprojection errors...

**Comment by SongBiaoVision** [comment]
Yes. I use pinhole-radtan. Is it anything wrong?

**Comment by chutsu** [comment]
Its just your cam-imu results have a large reprojection error. That could be:
1. Your camera distortions are not modelled well with radtan
2. Your calibration set isn't good, you could have "bumped" the rig on tha table causing a spike in accelerometer data or you didn't excite your camera enough to coverge to a good solution.

**Comment by SongBiaoVision** [comment]
Do you mean I should move camera with enough angles to activate all the axes.

**Comment by chutsu** [comment]
Most certainly! 

If I'm correct, you are supposed to move the camera rig while exciting all axes (don't forget to rotate), and move in such a way you don't introduce motion blur. Remember if you have blurry images in the calibration set you increase reprojection errors! And most important of all, don't bump the rig on anything, spikes ruins your calibration.

Doing calibration sucks...

**Comment by SongBiaoVision** [comment]
In order to calibrate camera and IMU. If I move the camera rig to exciting all axes. the calibration plate could move out of the camera vision! So I just move the camera in a little angle.

**Comment by SongBiaoVision** [comment]
Yours sincerely!
         A question is the IMU and camera should be synchronous. But why the rate of camera is 40hz and rate of IMU is 200hz in the paper.In the paper It is described the whole sensor suite is synchronized based on the trigger signal from the IMU. How to do it?
          Looking forward to hearing from you soon!

**Comment by kartikmohta** [comment]
For our setup, we have the IMU running at 200Hz and the camera is triggered every 5 IMU measurements giving us a 40Hz camera fps. The main thing to make sure for any setup is that the timestamps for the camera and IMU are correct. Ideally you don't want to timestamp the image after receiving it from the USB, it should have the timestamp based on when it was captured. The IMU triggering allows us to know exactly which IMU measurement triggered the image capture and hence put the correct timestamp for the image.

**Comment by chutsu** [comment]
I just wanted to add in case you guys don't know, but the MPU 6050 has a Digital Low Pass Filter (DLPF) (page 13 of 46, in [here](https://www.invensense.com/wp-content/uploads/2015/02/MPU-6000-Register-Map1.pdf)), in the above calibration results I set mine to `DLPF_CFG = 0` since I wanted to minimize any delays but currently I'm experiencing a lot of calibration errors __possibly__ (can be other factors) due to this.

![dlpf-configurations](https://user-images.githubusercontent.com/91460/38141547-9e36ad54-3406-11e8-91bf-a395f262d28f.jpg)

Might want to double check what the `MYNY-EYE camera` sets that value to, and additionally Kalibr's Camera-IMU extrinsic calibration has the option to do time calibration via the `--time-calibration` flag (I think this estimates the time delay between camera and imu msgs).

It would be interesting to know what the MARS Lab do specially that allows the MSCKF to fuse consumer grade IMUs, since they demonstrated it working on cellphone data.

**Comment by patrickpoirier51** [comment]
@chutsu  Would you please provide your imu.yaml file ? I am having a hard time finding the right numbers, here is what I found for the MPU9250 (thats is the one I am presently using , should receive a MPU6050 for more tests)

#Accelerometers
accelerometer_noise_density: 2.24e-03   #Noise density (continuous-time)
accelerometer_random_walk:   7.53e-05   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     18.4e-03   #Noise density (continuous-time)  
gyroscope_random_walk:       1.08e-05   #Bias random walk

cam_overlaps: [0]
rostopic:                    /imu0      #the IMU ROS topic
update_rate:                 200.0      #Hz (for discretization of the values above)

**Comment by chutsu** [comment]
Here is the `imu.yaml` I used:

```
# Accelerometers
accelerometer_noise_density: 0.661510573734  # Noise density (continuous-time)
accelerometer_random_walk: 0.0116244166649  # Bias random walk

# Gyroscopes
gyroscope_noise_density: 0.0256803279043  # Noise density (continuous-time)
gyroscope_random_walk: 0.00110904563018  # Bias random walk

rostopic: /gvio/imu  # the IMU ROS topic
update_rate: 200.454215255  # Hz (for discretization of the values above)
```

**But be warned!** As mentioned previously I did not get good calibration results so I would not advise you use it. I've since moved on to a much higher quality IMU (Xsens MTi-30) due to its synchronization features, I would suggest the same for you too to start. I don't know how sensitive MSCKF is w.r.t small delays between IMU and camera, but from what I gather (by reading Lee Clement's "[Battle for filter supremacy](http://www.starslab.ca/wp-content/papercite-data/pdf/2015_clement_battle.pdf)" paper) MSCKF has a higher hyper-parameter sensitivity (such as max window size, initial covariances, etc) compared to a Sliding window EKF slam formulation according to Clement.

**Comment by patrickpoirier51** [comment]
Thanks for the info, I see that the VIO experimentrers can be splitted  in 2 groups:
A) Those, like me, who try to go on budget with consumers IMU and low grade cameras
B) Those who consider that loosing time trying to make it work make it, at the end of day, more expensive that going with the real stuff 

I might switch to the second group.....

**Comment by chutsu** [comment]
Yeah, that would be best. Had this implementation formulation included the camera calibration parameters in the state vector maybe a consumer grade IMU would work. An example of MSCKF working with a consumer grade IMU would be Michael Shelley's Master thesis "[Monocular Visual Inertial Odometry on a Mobile Device](https://vision.in.tum.de/_media/spezial/bib/shelley14msc.pdf)", where in the formulation he included camera calibration parameters (intrinsics and extrinsics to imu), as well as modelling the camera's rolling shutter and time delay between camera and imu (see video [here](https://www.youtube.com/watch?v=Xrq56SZONvo))

Too bad he didn't open source his work.

**Comment by JJQ7** [comment]
Hi,  Thank you for sharing these. I also test software with MYNT-EYE and it woks despite some drift. @ke-sun  I have communicated with the manufacturer and confirmed that the date of the imu has passed through a low-pass filter before beening published. So I guess the imu data may not be correct when moving fast. However, I am troubled by another problem. When I use kalibr tools to get the device parameters, the results always seem to be a bit strange. The linear extrinsics of  T_cam_imu (both two cameras)  is always larger than 10cm. So I can only manually set the linear extrinsics which is not satisfactory. Any guidance on this would be helpful.
Thanks

**Comment by pxlong** [comment]
@JJQ7  I think the baseline of MYNT-EYE is ~12cm.

**Comment by JJQ7** [comment]
@pxlong 
cam0:
  T_cam_imu:
  - [0.03141391839908614, 0.9990276297077322, 0.030934783195746614, 0.09760518896993493]
  - [-0.9968469808852675, 0.029059043268037543, 0.07383541632763808, 0.008023737306668806]
  - [0.07286468575891122, -0.03315670497649925, 0.9967905349090944, -0.1664855591587721]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.44710914719658085, 0.18273618105454906, 0.00023988488891641717,
    0.00042680877040570693]
  distortion_model: radtan
  intrinsics: [698.2545761601818, 698.4788156363667, 361.26719886981266, 252.16448923976407]
  resolution: [752, 480]
  rostopic: /left/image_raw_color

**Comment by JJQ7** [comment]
I am sorry that my description is not clear enough. I mean the vector between the IMU coordinate system and the camera coordinate system is not correct. Rather than the vector between two camera coordinate systems.

**Comment by JJQ7** [comment]
I adjust the parameters of IMU and get strange results.
[report-imucam-dynamic.pdf](https://github.com/KumarRobotics/msckf_vio/files/1887499/report-imucam-dynamic.pdf)

**Comment by chutsu** [comment]
@JJQ7, yes your mean reprojection errors are way too high (you got ~6px, you should aim to get less than 0.8), and the acceleration and gyroscope errors are not within the error bounds, so I would not expect your calibration results to be correct.

Lastly, your imu parameters: 

```
 Accelerometer:
 Noise density: 0.0011809
 Noise density (discrete): 0.0264057267463
 Random walk: 8.2583e-05

 Gyroscope:
 Noise density: 7.2396e-05
 Noise density (discrete): 0.00161882377299
 Random walk: 1.3e-05
```

the noise density and random walk numbers are way too small (I could be wrong) which explains your calibration results. I have already posted my `imu.yaml` above.

**Comment by JJQ7** [comment]
@chutsu I'm really sorry that I uploaded the wrong calibration above.
[report-imucam-dynamic.pdf](https://github.com/KumarRobotics/msckf_vio/files/1888770/report-imucam-dynamic.pdf)

Although the repojection errors are smaller, the transformation between camera and imu is no correct.  The distance between the origin of camear coordinate system and the origin of imu coordinate system is larger than the actual value.

In addition, I suspect that there may be some problems with my recorded files. Because the sample time is too long.  How long should I sample? In order to prevent problems caused by cameras calibaration, I upload the relevant documents below.
[report-cam-image.pdf](https://github.com/KumarRobotics/msckf_vio/files/1888828/report-cam-image.pdf)

**Comment by chutsu** [comment]
That looks more reasonable. 

I don't have a good answer to how long your calibration sample should be, you might want to direct that to Kalibr team themselves, additionally you can have a look at their sample IMU-Camera calibration sample dataset to get an idea what the recorded calibration bag should be like ([here](https://github.com/ethz-asl/kalibr/wiki/downloads)). I usually collect multiple bags and run it through Kalibr and pick the one the seems the best. If there's a good method to validate IMU-camera calibration I'd love to know.

**Comment by JJQ7** [comment]
Thank you very much for your reply! I will contact with them later. 

By the way,  has anyone tried msckf with  3DM-GX3, 3DM-GX4 or 3DM-GX5 (IMU)?  Does anyone know the performance of these devices? Thanks!

**Comment by jian-li** [comment]
Although I have not yet tested msckf_vio on my VIO suite, as it need stereo configuration, but when i test realsense with VINS-Mono, the most important thing to have good performance is to make the device hardware synchronized if the algorithm doest not consider the device timing related issue.

**Comment by JJQ7** [comment]
I'm very sorry that I have been busy with my undergraduate thesis work recently so I could only spare a little time to experiment. I strongly agree that hardware synchronized has a greater impact on visual inertial system. But now I have another question. After hardware synchronized the imu and image, is it necessary to adjust the timestamp of image according to the imu trigger time? Thanks!

**Comment by Ajithkumar1** [comment]
Hi all, 
I am also facing this issue. The pose drifts after some time even when the camera is stable. I am sure that the camera is perfectly synced. 

@SongBiaoVision , Were you able to get good results after proper calibration?

**Comment by tiralonghipol** [comment]
@Ajithkumar1  what firmware version are you using? 
Any news on this ?
Thanks

**Comment by chutsu** [comment]
What calibration did you guys have in terms of reprojection errors? I built a custom stereo rig and was able to get some good results.

**Comment by tiralonghipol** [comment]
@chutsu are you hardware triggering?
I think that's the best way to get good results.. 
I'm using a Mynteye camera, which is declared 'hardware syncronized'..

**Comment by chutsu** [comment]
Indeed I am hardware triggering. I believe most SLAM formulations assume you have hardware triggered cameras and imu unless they explicitly state otherwise.

**Comment by tiralonghipol** [comment]
@chutsu  @Ajithkumar1 @JJQ7 
Actually I got the device working properly, checkout
https://www.youtube.com/watch?v=oCPwlf-6UJ8
and
https://www.youtube.com/watch?v=pxTjmilWQF4&feature=autoshare

**Comment by ghost** [comment]
@tiralonghipol Can you share your config files obtained after camera-imu calibration,?

**Comment by tiralonghipol** [comment]
> I agree that the quality of IMU measurements is very important for the estimation quality. We are using PointGrey CM3-U3-13Y3M-CS (2.8mm focal length) cameras and VectorNav VN100 IMU. Here are the typical calibration results from Kalibr for our configuration,
> 
> ```
> Calibration results
> ===================
> Reprojection error squarred (cam0):  mean 0.0258226320892, median 0.0147480323833, std: 0.0503808357645
> Reprojection error squarred (cam1):  mean 0.0256774901704, median 0.0129226561016, std: 0.0823128228942
> Gyro error squarred (imu0):          mean 0.0937716434596, median 0.0460440702065, std: 0.116936249636
> Accelerometer error squarred (imu0): mean 0.170679362745, median 0.109385920057, std: 0.172495253431
> ```
> It seems MYNT-EYE also uses MPU 6050.

Can you share details about the lenses you used on the poingreys?
thanks!

**Comment by ke-sun** [comment]
@kartikmohta

**Comment by kartikmohta** [comment]
These are the lenses we used: https://www.arecontvision.com/product/Lenses/MPM2.8A.

**Comment by moshanATucsd** [comment]
@tiralonghipol Hi, are you doing camera synchronization only or cam-imu synchronization? If you are using cam-imu synchronization, could you kindly advice how to do it?

**Comment by tiralonghipol** [comment]
I ordered all the material to replicate the configuration described in this repo. As soon as I get it all I'll let you know

**Comment by chenwinki** [comment]
@SongBiaoVision  Hello , have you deal with your problem "when I run msckf algorithm on the device,I get some quesitons. if device stay static,the positing of device is accurate, but if I move the device around, the position of the device drifts bad",  I meet the same problem , could you give me some advice. Thank you .

**Comment by nicotho** [comment]
@ke-sun 
Hi,
Could you please share the following parameters for the vectornav 100

accelerometer_noise_density: 0,001373 #continous
accelerometer_random_walk:  ?
gyroscope_noise_density: 0,000061056
gyroscope_random_walk: ?

Although we have the density parameters we would like to know what numerical values you used for the random walk parameter when calibrating with kalibr.

Any help is welcome!

Thank you,
Nicolas

**Comment by ke-sun** [comment]
These are the parameters we use (probably the default ones).
```
# Accelerometers
accelerometer_noise_density: 0.02   # Noise density (continuous-time)
accelerometer_random_walk:   0.0004 # Bias random walk

# Gyroscopes
gyroscope_noise_density:     0.010   # Noise density (continuous-time)
gyroscope_random_walk:       8.0e-06 # Bias random walk
```

**Comment by shmm91** [comment]
@SongBiaoVision  Have you solved you problem? I meet the same problem with you, my device is MYNT-EYE-D.
