### ISSUE TITLE
[ WARN] [1521047295.476425950]: Update change is too large.

### ISSUE THREAD

**Issue by gyjun0230** [KumarRobotics/msckf_vio#23]
Hello, when i run the program in our dataset, the program output  "Update change is too large". the result is bad。 Where is the reason? thanks~

**Comment by ke-sun** [comment]
Are you running the software with the EuRoC dataset? If yes, the problem is probably you are compiling in the debug mode.

**Comment by liutianxia** [comment]
hello, I want to know that why the program have different results in debug and release mode? Because I use part of the code, and I'm not sure if this will influence the results.
