### ISSUE TITLE
how to run msckf_vio?

### ISSUE THREAD

**Issue by Jhon82** [KumarRobotics/msckf_vio#25]
thanks very much for this project. 
I have successfully build using "catkin_make --pkg msckf_vio --cmake-args -DCMAKE_BUILD_TYPE=Release", the thing is how could I run this program?
some one mentioned " roslaunch msckf_vio msckf_vio_euroc.launch" , but where could I find this "msckf_vio"?  which path should I add to the ROS_PACKAGE_PATH?
ps: I'm a totally newbie about this ros thing.

**Comment by SongBiaoVision** [comment]
First you need to run "$source devel/setup.bash" in your workspace. I wish it will help you.

**Comment by chutsu** [comment]
Added a little bit more instructions in the README, if you're still struggling please make sure you go through the ROS tutorials first. [link](http://wiki.ros.org/ROS/Tutorials)

**Comment by hhmaizi** [comment]
thanks a lot, I will try.
