### ISSUE TITLE
loop-closure problem

### ISSUE THREAD

**Issue by SongBiaoVision** [KumarRobotics/msckf_vio#27]
Why don't you need loop-closure to get reposition of MAV to decrease the accumulative error？(such as mono vins). Is there some reasonable reason to explain it.

**Comment by chutsu** [comment]
This is not their main focus, their main focus was to create a filter based VIO that runs real time with competitive results to OKVIS. Many things can be done, but it just wasn't their focus from the paper they published.

**Comment by SongBiaoVision** [comment]
Ok. I get it. Thank you.
