### ISSUE TITLE
Hardware setup with cam_imu_sync

### ISSUE THREAD

**Issue by vcmman** [KumarRobotics/msckf_vio#35]
Hi, Sun Ke,

Thanks for your great job and open source sharing. We would like to repeat your result with the same hardware configuration in your paper. We notice that there is a 'cam_imu_sync' repo in this github account. I'm wondering if you use the same package to publish messages for msckf_vio. Is there any documentation somewhere to explain the tricks for your setup.

Regards

**Comment by ke-sun** [comment]
Unfortunately, the `cam_imu_sync` repo is deprecated. We have described the hardware configuration in our paper. You could take a look at that.

**Comment by moshanATucsd** [comment]
Hi @ke-sun, so cam_imu_sync is not used for msckf_vio right? I am wondering what is the package used for synchronization in msckf_vio?
