### ISSUE TITLE
random index generation problem

### ISSUE THREAD

**Issue by jackiecx** [KumarRobotics/msckf_vio#36]
In the function twoPointRansac, the two point index is generated as following:
`
int pair_idx1 = raw_inlier_idx[random_gen.uniformInteger(0, raw_inlier_idx.size()-1)];
int idx_diff = random_gen.uniformInteger(1, raw_inlier_idx.size()-1);
int pair_idx2 = pair_idx1+idx_diff < raw_inlier_idx.size() ? pair_idx1+idx_diff : pair_idx1+idx_diff-raw_inlier_idx.size();
`

the pair_idx1 is a member of raw_inlier_idx, the pair_idx2 is not a member of raw inlier_idx.
I suspect that pair_idx2 should also be a member of raw_inlier_idx.

**Comment by ke-sun** [comment]
That's a nice catch. Thanks =P
