### ISSUE TITLE
JPL quaternion to Hamilton ?

### ISSUE THREAD

**Issue by jackiecx** [KumarRobotics/msckf_vio#37]
The msckf_vio use JPL quaternion. That's quite strange as both eigen and ros use Hamilton.
Is there any future plan to change JPL quaternion to Hamilton ?
Or, is there any reference material ?
Thanks.

**Comment by tomas789** [comment]
Although I cannot say for the authors but what would be the advantage of conversion here? It might not be obvious at first glance but majority of the formulas would need to be derived again and debugged again. The total effort in doing so would be somehow comparable to writing the whole thing from scratch. I'd say the slight advantage of having Hamilton notation just doesn't pay off. Plus all the literature on MSKCF uses JPL notation and it might actually obfuscate things more then it would help.

**Comment by jackiecx** [comment]
> Plus all the literature on MSKCF uses JPL notation

That sounds reasonable
