### ISSUE TITLE
About processModel function

### ISSUE THREAD

**Issue by gyjun0230** [KumarRobotics/msckf_vio#38]
hi, I'm confused about the Modify the transition matrix in processModel. Do you have some introductory notes or references paper?
![image](https://user-images.githubusercontent.com/13348062/40959520-7df7a07c-68cf-11e8-9ffb-ce3bda650a48.png)

**Comment by tomas789** [comment]
Don't take what I way for granted but this comment is regarding the whole block of code. The original version of MSCKF from 2007 has incorrect observability properties. There are multiple ways of fixing this issue. You can read more in the paper. In this particular work, OC-KF was used. And this bit is its realization.
