### ISSUE TITLE
what references used in your code for equations 

### ISSUE THREAD

**Issue by chenwinki** [KumarRobotics/msckf_vio#40]
Hi ,what references used in your code for equations ,you just use some annotation like "// Compute hi1, hi2, and hi3 as Equation (37)." thanks very much!

**Comment by ke-sun** [comment]
Take a look at,
A. I. Mourikis and S. I. Roumeliotis, “A multi-state constraint kalman filter for vision-aided inertial navigation,” Robotics and automation, 2007 IEEE international conference on, pp. 3565–3572, 2007.

The exact equation no. may not match.
