### ISSUE TITLE
measurement error!

### ISSUE THREAD

**Issue by chenwinki** [KumarRobotics/msckf_vio#44]
Hi ,thanks for your code!
I used evo tool get .txt file(contain: timestamp,position,orientation) of groundtruth for V1_01_easy of euroc.
and get another .txt file(contain: timestamp,position,orientation) from msckf_vio , and use the tools for the RGB-D benchmark(https://vision.in.tum.de/data/datasets/rgbd-dataset/tools#evaluation) to compute the relative pose error , the result is follow:
![plot](https://user-images.githubusercontent.com/40333150/42122056-8287694e-7c6e-11e8-9062-823d847b4e08.png)
the error is too large , do you have some compare about rotation/translation ? what do you think about this result?

**Comment by ke-sun** [comment]
Usually the position error should keep increasing. It is odd that the error in the figure starts from 0 and ends at 0 as well. The RMSE for the EuRoC dataset is reported in the paper if you want any reference.

**Comment by chenwinki** [comment]
thank you! I will recheck my procedure.
