### ISSUE TITLE
Tool for evaluation of result of VIO

### ISSUE THREAD

**Issue by chenwinki** [KumarRobotics/msckf_vio#45]
Dear author:   could you please commend suggest tool for comparing/measuring the Metrics of VIO, or what tool did you used in the paper? thank you !

**Comment by AbyssGaze** [comment]
You could refer to https://vision.in.tum.de/data/datasets/rgbd-dataset/tools
or https://github.com/uzh-rpg/rpg_trajectory_evaluation
