### ISSUE TITLE
covariance update equation

### ISSUE THREAD

**Issue by sunbingfeng** [KumarRobotics/msckf_vio#46]
The right equation to update covariance matrix may be the one attached as follows:

<img width="908" alt="screen shot 2018-07-04 at 10 51 50 am" src="https://user-images.githubusercontent.com/9302004/42364805-11eadcfa-812f-11e8-94bc-d8e7d824e6d6.png">

But in your code , you used a simplified one, and commented out the right one.

```
void MsckfVio::measurementUpdate(
    const MatrixXd& H, const VectorXd& r) {
...
  // Update state covariance.
  MatrixXd I_KH = MatrixXd::Identity(K.rows(), H_thin.cols()) - K*H_thin;
  //state_server.state_cov = I_KH*state_server.state_cov*I_KH.transpose() +
  //  K*K.transpose()*Feature::observation_noise;
  state_server.state_cov = I_KH*state_server.state_cov;
...
```

I am thinking if you have tried to use the right one, but it did not work as expected?

Thanks!

**Comment by ke-sun** [comment]
Please correct me if I am wrong. I though the two equations are equivalent if K is the optimal Kalman gain. The advantage of the uncommented code is less operation.

**Comment by sunbingfeng** [comment]
I found a trustworthy explanation in Paper(`Quaternion kinematics for the error-state Kalman filter`, P63).

![Screenshot 2019-05-09 at 4 05 12 PM](https://user-images.githubusercontent.com/9302004/57437422-53403380-7274-11e9-9d36-84db2c911230.png)
