### ISSUE TITLE
Synchronization between camera and IMU

### ISSUE THREAD

**Issue by moshanATucsd** [KumarRobotics/msckf_vio#48]
In msckf_vio.h 

```
    // IMU data buffer
    // This is buffer is used to handle the unsynchronization or
    // transfer delay between IMU and Image messages.
    std::vector<sensor_msgs::Imu> imu_msg_buffer;
```

which seems that msckf could handle unsynchronization between camera and IMU. So I am wondering why we still need hardware synchronization as mentioned in  #22?

Also, what should be the precision of the synchronization?

**Comment by mzahana** [comment]
I am also interested to what is meant by synchronization here?
Is it that the two cameras are hardware triggered to capture at the same time? but then how is it synchronized against IMU?

Or, it means that the two images and the IMU data are stamped accurately against the same clock reference ?

Thanks.

**Comment by snakehaihai** [comment]
use a higher rate imu? if ur imu rate is 800hz. then should have no problem approx

**Comment by chenwinki** [comment]
@snakehaihai my imu is 800hz, and camera is 15hz, and I use the calibrate result from kalibr, the timeoffset is about 0.1s, When I run msckf ,the drift is very large,and the result is very bad . could you give me some hint?

**Comment by snakehaihai** [comment]
@chenwinki  
First of all. not sure ur offset is inter-camera or inter camera/imu. But anyway sounds to me you didn`t sync them. 
Have you tried to use a microcontroller to do the sync?  For multiple sensors, I always do this sort of sync. 

For example. both vectorNav 100 and ueye 1221 allow external trigger. Just aim at the correct timing to send the pulse.  

If u use DJI A3 it comes with external trigger to the camera. 

0.1s is impossible to run.

**Comment by chenwinki** [comment]
@snakehaihai Thank you for your reply. I use zed mini which contains imu and cameras , I can't dothe hardware sync. the time offset is inter camera/imu, whether I can handle this timeoffset in the code?

**Comment by snakehaihai** [comment]
It sounds like the delay is from the image using V4L driver. I didn`t use ZED on the drone because there is an image delay. 
In ur case,   For each imu reading. put them in a buffer. Adjust the buffer size which causes 0.1 sec delay. It might not be correct to ms but surely better than 0.1 sec

**Comment by chenwinki** [comment]
@snakehaihai  I'm sorry , I don't get your "Adjust the buffer size which causes 0.1 sec delay". do you mean add 0.1s to the every imu msgs' head.stamp?

**Comment by snakehaihai** [comment]
@chenwinki You can do it that way as well.

**Comment by chenwinki** [comment]
@snakehaihai Oh, Thank you !

**Comment by msamogh** [comment]
Any luck with this, @chenwinki?
