### ISSUE TITLE
Performance on KITTI datasets

### ISSUE THREAD

**Issue by salahkhan94** [KumarRobotics/msckf_vio#49]
Has anyone tested MSCKF on the KITTI datasets ? or any other On-Road recorded datasets where movement is not strictly speaking 6DOF ?

**Comment by tomas789** [comment]
In case of the KITTI dataset, the cameras are synchronized to the LIDAR and the IMU samples the measurements independently. So it would take a bit of effort to get it work. It would not work out of the box. At least not with the same accuracy as in case of the synchronized datasets.

**Comment by salahkhan94** [comment]
Ah, I see ! I haven't tested it on any ground recorded data yet but considering tight synchronisation between IMU and Cameras, do you reckon there could be other issues considering there is "smooth and steady" motion in only 2D ?

ROVIO has scale issues when it comes to steady motion as IMU is not excited. Ideally MSCKF mustn't have scale problems considering a Stereo setup but I just want to know if anyone faced issues other than synchronization on ground. 
I'll post here the results once I test it on ground datasets.

**Comment by moshanATucsd** [comment]
Hi, how about the synchronized data for kitti, will it be able to work? I think it won't because msckf requires the first 200 IMU data for initialization. Have you tested it on kitti? @salahkhan94
