### ISSUE TITLE
Could stereo matching get better?

### ISSUE THREAD

**Issue by lastsongforu** [KumarRobotics/msckf_vio#50]
I found the optical flow matching between left and right cameras performed not so well when facing some scenes. 
Sometimes only less than half points could be matched in another camera.
Would this influence the final performance?

**Comment by snakehaihai** [comment]
Make sure they are synced. then check calibration? make epl plot? u sure 2 camera is at same focus length ?

**Comment by Shane922** [comment]
Hi, I find the same problem in stereo matching of VINS-Fusion, do you get some solutions?
