### ISSUE TITLE
Test msckf_vio using oCams-VI-sensor

### ISSUE THREAD

**Issue by Orionku** [KumarRobotics/msckf_vio#52]
I have tested the msckf_vio using oCams_sensor(oCams are synchronized). But the msckf_vio trajectory is not smooth. When the VI_sensor moved straight, the trajectory have some jagged jitter. Also, when rotating in place, the path moves left, right or back and forth. When I come back to the starting point, the error is very large. I calculated camera and IMU extrinsic using the VI_sensor datasheet. I don't know what to do here. Could someone please let me know?  Here is my data bag file, and my sensor parameter.(https://drive.google.com/drive/folders/1jOccq6zpnw10A2X-Km4f6vJa7_lfHPrG?usp=sharing)

**Comment by Orionku** [comment]
Dear author
What is 'initial_covariance/extrinsic_rotation_cov' and 'initial_covariance/extrinsic_translation_cov'? 
How do I get this value? Could someone please let me know?

**Comment by kartikmohta** [comment]
Those are the initial covariances for the left camera to IMU extrinsics. The filter state contains these extrinsics and they are estimated (refined) online but we definitely recommend having a good initial value for them from a camera-IMU calibration.

**Comment by Orionku** [comment]
Thanks for your reply.
Could you tell me more about how 'extrinsic_rotation_cov 'and 'extrinsic_translation_cov' can be obtained from camera-IMU calibration??? Can I get it using the kalibr tool? It looks like it is not in the resulting file. Could you give me the details?
