### ISSUE TITLE
Running on Odroid

### ISSUE THREAD

**Issue by mzahana** [KumarRobotics/msckf_vio#53]
Hi.

Can this package run on odroid xu4?

**Comment by kartikmohta** [comment]
Yes, should work, just that you'll have to use a lower frame rate (around 20fps) since the processor is weaker than an Intel one.

**Comment by mzahana** [comment]
Thanks. I will give it a try.

**Comment by kartikmohta** [comment]
@mzahana Closing this issue for now, you can reopen it if you find any problems.
