### ISSUE TITLE
how to get good performance on euroc dataset

### ISSUE THREAD

**Issue by pxlong** [KumarRobotics/msckf_vio#6]
Hi, I am running this algorithm on euroc dataset. I follow the steps as below:
`rviz -d rviz_euroc_config.rviz`
`roslaunch msckf_vio msckf_vio_euroc.launch`
`rosbag play V1_02_medium.bag`

But the performance is not good, as you can see here: https://youtu.be/VqYoSveIdI4. This result is not comparable to https://www.youtube.com/watch?v=OXSB8Bze0cY. 

Can you please give some hints to get better performance?

**Comment by kartikmohta** [comment]
Did you compile the package in Release mode? The standard `catkin_make` does not enable optimizations which leads to bad performance. Use `catkin_make -DCMAKE_BUILD_TYPE=Release`.

**Comment by pxlong** [comment]
Thanks, Kartik. It works well after compiling in Release mode.  
Sorry, I did not notice that.

**Comment by pxlong** [comment]
Hi @kartikmohta, I suggest to set the default **CMAKE_BUILD_TYPE** flag to **Release** in the CMakeLists.txt with: 

```
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif(NOT CMAKE_BUILD_TYPE)
```

**Comment by edgar-explorer** [comment]
@pxlong  I followed your setps, but I cannot get the map.
[ WARN] [1515588182.371265541]: MessageFilter [target=map ]: Dropped 100.00% of messages so far. Please turn the [ros.rviz.message_notifier] rosconsole logger to DEBUG for more information.
![screenshot from 2018-01-10 20-46-25](https://user-images.githubusercontent.com/24315713/34773630-5ba7e13a-f647-11e7-8bea-aab18fa2ac57.png)

**Comment by ke-sun** [comment]
@cumtchenchang 

The `fixed_frame_id` is set to `world` by default in the `msckf_vio_euroc.launch`. You can either change the launch file or change the fixed frame in rviz to fix this problem. Or more conveniently, you can use the rviz configuration files in the `rviz` folder.

**Comment by edgar-explorer** [comment]
@ke-sun 
Thank you for your help.
I read your paper, how to change your cold to output dataset  trajectory, I want to compare your method with our lab method.

**Comment by SkyRiderMike** [comment]
I load the configuration file in rviz folder for euroc dataset, but no trajectory show. However, it has some front-end feature tracking in the image window
