### ISSUE TITLE
Simplifying the code a tad that initializes the IMU attitude

### ISSUE THREAD

**Issue by chutsu** [KumarRobotics/msckf_vio#60]
In `MsckfVio::initializeGravityAndBias()`, from line [278](https://github.com/KumarRobotics/msckf_vio/blob/master/src/msckf_vio.cpp#L278), the idea is to initialize the IMU initial attitude by forming a quaternion from two vectors, the gravity vector `IMUState::gravity` and averaged accelerometer measurement `gravity_imu`.

```
Quaterniond q0_i_w = Quaterniond::FromTwoVectors(
    gravity_imu, -IMUState::gravity);
  state_server.imu_state.orientation =
    rotationToQuaternion(q0_i_w.toRotationMatrix().transpose());
```

Instead of transposing the rotation matrix produced from `q0_i_w`, would it not be simplier to just rearrange from

``` 
Quaterniond::FromTwoVectors(gravity_imu, -IMUState::gravity)
```
to:
``` 
Quaterniond::FromTwoVectors(-IMUState::gravity, gravity_imu)
```
swapping the order of the two vectors.  Which would remove the need for transposing the matrix, resulting in:
```
Quaterniond q0_w_i = Quaterniond::FromTwoVectors(-IMUState::gravity, gravity_imu);
state_server.imu_state.orientation = rotationToQuaternion(q0_w_i.toRotationMatrix());
```

Small Octave script [here](https://rextester.com/ZSTDZN31099)

**Comment by ke-sun** [comment]
Yes, your way is simpler. Thanks for pointing that out.
