### ISSUE TITLE
 About stateAugmentation()

### ISSUE THREAD

**Issue by struggleforbetter** [KumarRobotics/msckf_vio#67]
![910037413](https://user-images.githubusercontent.com/44396493/49126055-371b8c00-f2fd-11e8-9681-99c905032d6b.jpg)
`
Matrix<double, 6, 21> J = Matrix<double, 6, 21>::Zero();
  J.block<3, 3>(0, 0) = R_i_c;
  J.block<3, 3>(0, 15) = Matrix3d::Identity();
  J.block<3, 3>(3, 0) = skewSymmetric(R_w_i.transpose()*t_c_i);
  //J.block<3, 3>(3, 0) = -R_w_i.transpose()*skewSymmetric(t_c_i);
  J.block<3, 3>(3, 12) = Matrix3d::Identity();
  J.block<3, 3>(3, 18) = Matrix3d::Identity();
`

**Comment by minxuanjun** [comment]
@struggleforbetter you can test this code
   J.block<3, 3>(3, 0) = -R_w_i.transpose()*skewSymmetric(t_c_i);
    J.block<3, 3>(3, 12) = Matrix3d::Identity();
    J.block<3, 3>(3, 18) = R_w_i.transpose();

**Comment by struggleforbetter** [comment]
> @struggleforbetter you can test this code
> **J.block<3, 3>(3, 0) = -R_w_i.transpose()*skewSymmetric(t_c_i);**
> J.block<3, 3>(3, 12) = Matrix3d::Identity();
> J.block<3, 3>(3, 18) = R_w_i.transpose();

**J.block<3, 3>(3, 0) = R_w_i.transpose()*skewSymmetric(t_c_i);**
I think there is no minus
