### ISSUE TITLE
PLUGINLIB_DECLARE_CLASS ERROR

### ISSUE THREAD

**Issue by JeffreyYH** [KumarRobotics/msckf_vio#69]
when compiling, there was an error shown like this: 

`error: expected constructor, destructor, or type conversion before ‘(’ token PLUGINLIB_DECLARE_CLASS(msckf_vio, ImageProcessorNodelet, msckf_vio::ImageProcessorNodelet, nodelet::Nodelet); `

How can I solve this problem? I am using Ubuntu 18.04 and ROS Melodic. Thank you!

**Comment by realdealneil** [comment]
I second this question...the code compiles fine in 16.04, but something breaks about the way nodelets are used in 18.04 (I got the same error that @JeffreyYH mentions above).  I looked a little into the ros pluginlib documentation, but it's a bit scarce.

**Comment by msamogh** [comment]
I've fixed it in #72

**Comment by Akashleena** [comment]
Having the same problem in ROS Noetic and Ubuntu 20.04 and it solved by replacing PLUGINLIN_DECLARE_CLASS with PLUGINLIB_EXPORT_CLASS
