### ISSUE TITLE
Quickly lose track on EuRoC Vicon sequences and release mode

### ISSUE THREAD

**Issue by YipuZhao** [KumarRobotics/msckf_vio#70]
I was trying to reproduce some of the results for msckf on EuRoC sequences, with the scripts provided from this repo.  While the output looks reasonable initially (e.g. the green dots), the odom estimation quickly blows up after the MAV takes off (e.g. the red dots).
![image](https://user-images.githubusercontent.com/1567526/49710541-16f6a180-fc08-11e8-8e59-238fbbc40c8c.png)
The package is built under release mode, and the image processing front-end is functioning:
![image](https://user-images.githubusercontent.com/1567526/49710536-1231ed80-fc08-11e8-8be7-b7ef4416fce2.png)

Is there anything I missed? Thank you for any suggestions or hints :)

**Comment by ke-sun** [comment]
Could you show some screen snapshots for the terminal while the software is running?

**Comment by YipuZhao** [comment]
@ke-sun Sure thing. Thank you for the help!
![image](https://user-images.githubusercontent.com/1567526/49744599-1ba07180-fc6b-11e8-8ac1-0af8f25fb462.png)

PS the full screen log is available via the dropbox link:
https://www.dropbox.com/s/dpma6355vc7h15o/on_screen_log.txt?dl=0

**Comment by ke-sun** [comment]
It seems the software is not compiled in release mode if you are using a normal laptop/desktop. Otherwise, the computer is probably slow, you have to dial down the number of features.

**Comment by YipuZhao** [comment]
Ah I see what's happening.  I was using a custom build opencv3 for my catkin workspace, which might not be built in Release mode.  Switching back to the kinetic default works.  Thank you for the suggestion!
