### ISSUE TITLE
trajectory drifts in flight

### ISSUE THREAD

**Issue by Tr-H** [KumarRobotics/msckf_vio#73]
Hello,

First, thanks for the open-source code. I run the msckf_vio on a UAV with FLIR FL3-U3-13E4C-C stereo cameras and MicroStrain 3DM-GX5-25 imu. The cameras are synchronized by external trigger at 20Hz. My camera-imu calibration results by kalibr is there
[report-imucam-2018-11-21-11-04-12.pdf](https://github.com/KumarRobotics/msckf_vio/files/2722995/report-imucam-2018-11-21-11-04-12.pdf)
But there are some problems with the setup of the noise of acc and gyro. How should I set it up?
I compared accelerometer data with the fla dataset.
![screenshot from 2019-01-03 11-12-13](https://user-images.githubusercontent.com/25916753/50628048-4aabb980-0f71-11e9-9815-e3886fb03128.png)

The result of msckf_vio is here. The red is the groundtruth and the green is trajectory from msckf_vio.
![result_1](https://user-images.githubusercontent.com/25916753/50627987-11734980-0f71-11e9-8b62-6fdb1aeba5de.png)
![result_2](https://user-images.githubusercontent.com/25916753/50628125-a37b5200-0f71-11e9-8398-c99ad28e9c6e.png)
![result_3](https://user-images.githubusercontent.com/25916753/50628127-a5ddac00-0f71-11e9-874f-a0b13bcb9837.png)
How should I improve my performance?

**Comment by ke-sun** [comment]
There are too many features set in the launch file. The update cannot be done in time. Reduce the number of features would help. Normally, around 50 features should be enough.

**Comment by Tr-H** [comment]
Thanks for your timely reply. I reduced the number of features to around 50, which are distributed in 50 grid like this
![req3](https://user-images.githubusercontent.com/25916753/50688716-b5d4b900-1061-11e9-9a27-e3e37e2a7a89.png)
![req4](https://user-images.githubusercontent.com/25916753/50688745-d7ce3b80-1061-11e9-8216-676d5cb90519.png)
The result of msckf_vio is here. The red is the groundtruth and the green is trajectory from msckf_vio.
![_20190104205405](https://user-images.githubusercontent.com/25916753/50689048-11ec0d00-1063-11e9-9132-9f2d543ffb5a.png)
![_20190104205427](https://user-images.githubusercontent.com/25916753/50689055-187a8480-1063-11e9-931c-1b2c8016c724.png)
![_20190104205432](https://user-images.githubusercontent.com/25916753/50689056-1b757500-1063-11e9-8b32-e9c000394209.png)
The UAV only runs within 3 meters, showing a large drift.

The strategy of camera exposure synchronization refers to your paper, Experiments in Fast, Autonomous, GPS-Denied Quadrotor Flight. 

The noise set in the launch file is here
![_20190104205437](https://user-images.githubusercontent.com/25916753/50689240-c2f2a780-1063-11e9-941d-e3a470427e7d.png)
Looking forward to your reply.

**Comment by ke-sun** [comment]
Does the problem still exist if the sensors are moved by hand (without turning on the props)? If the problem disappears, it is probably due to the significant IMU noise caused by the vibration of the props and motors. 

Be sure to start the software before turning on the props, since it reads IMU messages for a few seconds to determine the initial orientation, gravity magnitude, and gyro bias. If the software was started before the motors, probably a weak damper is need for the whole sensor package.

**Comment by ke-sun** [comment]
BTW, it is probably beneficial to recalibrate the cameras carefully. The reprojection error is a bit large. Normally, error should be under 1.0 pixel.

**Comment by Tr-H** [comment]
Thanks for your timely reply. The problem disappears when the sensors are moved by hand. I Recalibrated the sensors by kalibr and the reprojection error is about 0.8. The noise set is the same. The performance during the flight has been significantly improved. Thank you very much for your answer. 

But now I have another question that the trajectory drifts suddenly when camera's exposure time changing. There is some mutation in image brightness as the exposure time changes.

**Comment by ke-sun** [comment]
It is a common problem for stereo images. Our fix in the driver is to have the two cameras have the same exposure time with a customized auto-exposure time controller. See #41 for more details.

**Comment by Tr-H** [comment]
Thank you for your kindly help! I will adjust params of the exposure controller to improve the performance. Learn a lot from your reply~ Thanks again
