### ISSUE TITLE
How to judge whether the EKF filter is divergence?

### ISSUE THREAD

**Issue by qinyong5** [KumarRobotics/msckf_vio#75]
Hello, thanks for your great job and open source sharing.
I have a question. if the EKF filter is divergence when the UAV is flying. the navigation information given by MSCKF_VIO is inaccuracy, which may cause the UAV out of control. So how to detect whether the  EKF filter is  divergence accurately and quickly???

**Comment by ke-sun** [comment]
The covariance in the published odometry message should be a good place to look at.
