### ISSUE TITLE
add lidar measurement to msckf!

### ISSUE THREAD

**Issue by chenwinki** [KumarRobotics/msckf_vio#76]
Dear author: 
  Thank you for your open source.  I add lidar measurements to msckf,  I stop stereo update, just imu and lidar measurement , but it can't work.
  Could you give me some hint or experience how to use ekf for imu and measurement(visual or lidar). Thank you very much!

**Comment by jian-li** [comment]
If you fuse lidar raw point with camera and imu, you can refer to zhangji's work, https://www.ri.cmu.edu/ri-people/ji-zhang/. If you fuse lidar odometry relative pose with visual and imu, you can use lidar odometry pose as a measurement for msckf estimator.
