### ISSUE TITLE
About the track bias

### ISSUE THREAD

**Issue by RxhN** [KumarRobotics/msckf_vio#78]
Hi ,Thank you for you sharing.
I have some problem about track.
I use zed and xsen to runing . however,almost all of my track result have a little angle/heading bias. as the picture below.
I am waiting for your help.
![image](https://user-images.githubusercontent.com/22066471/54684033-24e48880-4b4e-11e9-8684-ecbf44b6eedd.png)
![image](https://user-images.githubusercontent.com/22066471/54684050-34fc6800-4b4e-11e9-87c7-5194451854d7.png)
![image](https://user-images.githubusercontent.com/22066471/54684058-3a59b280-4b4e-11e9-820f-3c00791ff011.png)

**Comment by ke-sun** [comment]
It is a common problem for vios. Either large or small, there is drift in yaw and position eventually. Tuning the noise parameters can help. But if drift-free is required, it is probably better to look for slam solutions.

**Comment by jian-li** [comment]
First, how well you imu and camera are synchronized, this should have big impact on the result. Second, vio is a odometry in nature, but for your situation that you run the system multiple times at the environment, you can build a map and track the map, this is the method that tango use, you can read the maplab project https://github.com/ethz-asl/maplab.
