### ISSUE TITLE
Can this work on Mono camera?

### ISSUE THREAD

**Issue by alongqiyue** [KumarRobotics/msckf_vio#8]
I found the feature position was triangulated by two camera views instead of stereo views, can this code work on mono camera+imu?

**Comment by ke-sun** [comment]
Unfortunately, the software cannot be used for monocular cameras.

**Comment by zpfriedel** [comment]
Why can't this be adapted to mono cameras? If the position is being triangulated between separate camera views at different instances and not between the stereo view at the same instance, can't the code just be modified to only take into account the feature observations of one camera?
