### ISSUE TITLE
Surviving no IMU messages

### ISSUE THREAD

**Issue by rocomanmelli** [KumarRobotics/msckf_vio#81]
Hi!

We are trying to run msckf_vio on the sequence 1 of this agricultural dataset: http://www.cifasis-conicet.gov.ar/robot/doku.php. We found a part in which the robot doesn't move so msckf_vio can initialize. After that, the system works pretty well untill a 0.3 s period of no IMU messages arrives. This is shown in the next rqt_bag capture:

![no_imu_msgs](https://user-images.githubusercontent.com/49685521/57648316-96174980-759b-11e9-8003-35997bb083a8.png)

In that moment, the estimated pose starts diverging as it is shown in this Rviz capture (in the image this can't be appreciated because I terminated the rosbag play execution but it diverges):

![diverge](https://user-images.githubusercontent.com/49685521/57648287-72ec9a00-759b-11e9-9428-edb2b1e745ca.png)

So the question is: Is there any way in which this could be avoided? With some different setup, for example? The configuration and launch files are posted here:

[config_launch.zip](https://github.com/KumarRobotics/msckf_vio/files/3174460/config_launch.zip)

Thanks in advance.

Román.

**Comment by andre-nguyen** [comment]
I can't comment on whether its possible but I thought the Rosario dataset wasn't tightly hardware synchronized between the images and the imu so there was no point in trying a visual-inertial algorithm on it.

**Comment by ke-sun** [comment]
It is reasonable that losing IMU msgs for 0.3s can cause divergence. Unfortunately, I don't have a good idea how to work around this. Maybe you can fake the IMU messages with Wheel odometry for this 0.3s :P, if possible.
