### ISSUE TITLE
No result from MSCKF_VIO

### ISSUE THREAD

**Issue by tekrajchhetri** [KumarRobotics/msckf_vio#87]
Based on read me in order to run vio the input required input topics are camera and imu input. I have stereo camera input and imu (shown below -- topic renamed). As suggested the robot starts from stationary state. But when I run I get nothing, it runs without error but unable to produce odometry or publish point cloud. Is there anything missing? 
![vio](https://user-images.githubusercontent.com/52251022/69059114-94807f80-0a1d-11ea-9b8a-b9e070b093be.png)

Thank you.

**Comment by kamzero** [comment]
I have the same question with you. Could you please tell me how did you solve it?

**Comment by tekrajchhetri** [comment]
@kamzero I do not remember completely but it if I am not mistaken the topics needs to be synchronised.

**Comment by kamzero** [comment]
Do you mean that the frequency of the same type of rostopic in different config files should be set to the same?
