### ISSUE TITLE
How can I get the output results files?

### ISSUE THREAD

**Issue by EmiyaEstelle** [KumarRobotics/msckf_vio#89]
Hi, I want to see the results of VIO such as positions and attitudes. I ran the codes of EuRoC Vicon Room 1 01 but did not see the results files. Could anyone tell me how to find them? Thank you!

**Comment by cheesekuntly** [comment]
@EmiyaEstelle  Hi,why did you close the issue?can you tell me how did you solve it?

**Comment by EmiyaEstelle** [comment]
@cheesekuntly 
Hi. I have recorded a rosbag with the topics of odometry messages to get the result.

**Comment by cheesekuntly** [comment]
Hello, I am a newbie, can you tell me how you modified the code
