### ISSUE TITLE
Could you please tell me how to evaluate the accuracy?

### ISSUE THREAD

**Issue by Nronaldo** [KumarRobotics/msckf_vio#92]
Thank you for you nice work.
I want to evaluate the accuracy, but I don't know how to output a trajectory txt to compare with the groundtruth of a rosbag. Could you please give me some advice about how to create the trajectory file? Thank you

**Comment by Nronaldo** [comment]
Now I modified publish function in msckf_vio.cpp and saved the time ,odom_msg.pose.pose.position, odom_msg.pose.pose.orientation in TUM data format. Then I use the TUM tool to evaluate the accuracy. But I wonder if the publish timestamp is right for evaluating accuracy?

**Comment by ke-sun** [comment]
The time stamp of the odom msgs is set based on the corresponding stereo image pairs.
