### ISSUE TITLE
If I want to modify the topic "cam[x]_image" to "usb_cam/image_raw", what codes should I modify?

### ISSUE THREAD

**Issue by sunt40** [KumarRobotics/msckf_vio#94]

**Comment by ke-sun** [comment]
What you want is probably remapping the image topics.
See the following line in `image_processor_euroc.launch` for an example.
https://github.com/KumarRobotics/msckf_vio/blob/e3a39a95b57da376924aa22b46637b60f68f504c/launch/image_processor_euroc.launch#L27

**Comment by sunt40** [comment]
I just found out that you used a stereo camera. Is it very difficult to change to a monocular camera?
