### ISSUE TITLE
T_b_w confusion

### ISSUE THREAD

**Issue by taogashi** [KumarRobotics/msckf_vio#98]
```c++  
IMUState::T_imu_body =
    utils::getTransformEigen(nh, "T_imu_body").inverse();
```
and
```c++
  Eigen::Isometry3d T_b_w = IMUState::T_imu_body * T_i_w *
    IMUState::T_imu_body.inverse();
```
So in the code:
- `T_i_w` transforms a vector in i frame to w frame
- `T_imu_body` transforms a vector in i frame to b frame

However in the configuration yaml file:
- `T_imu_body` transforms a vector in b frame to i frame

:rofl::rofl::rofl:

**Comment by ke-sun** [comment]
You are right. 
We start with a different naming convention from Kalibr. 
It's too late until we realize that.

**Comment by taogashi** [comment]
Thx, clear now.
