### ISSUE TITLE
Built on Xavier, how to demonstrate

### ISSUE THREAD

**Issue by JohnVorwald** [KumarRobotics/msckf_vio#99]
Hello,
  I am new to Xavier / CV.  
The command 
catkin_make --pkg msckf_vio --cmake-args -DCMAKE_BUILD_TYPE=Release

gives the error

CMake Error at /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake:113 (message):
  Project 'cv_bridge' specifies '/usr/include/opencv' as an include dir,
  which is not found.  It does neither exist as an absolute directory nor in
  '${{prefix}}//usr/include/opencv'.  Check the issue tracker
  'https://github.com/ros-perception/vision_opencv/issues' and consider
  creating a ticket if the problem has not been reported yet.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  msckf_vio/CMakeLists.txt:9 (find_package)

The error can be fixed by following
https://github.com/ros-perception/vision_opencv/issues/345

```
sh0w commented on Jul 24 • 
i had the same problem (jetson xavier + ubuntu 18.04 + ros melodic)

we fixed it like this:

change the file:

/opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake
change this line:

set(_include_dirs "include;/usr/include;/usr/include/opencv")
to

set(_include_dirs "include;/usr/include;/usr/include/opencv4")
```

With that modification, the command
catkin_make --pkg msckf_vio --cmake-args -DCMAKE_BUILD_TYPE=Release
runs to completion, and creates numerous targets including the following
[ 62%] Built target msckf_vio_generate_messages
[ 81%] Built target image_processor
[ 88%] Built target image_processor_nodelet
[ 92%] Built target msckf_vio
[100%] Built target msckf_vio_nodelet

I have a MYNT Eye S connected to the Xavier.  Can you provide instructions on how to do a real time demonstration.  I'm new to this topic.

**Comment by ke-sun** [comment]
It should not be too hard to run on Xavier.
You could try calibrating the cameras first.
Then modify the launch files connecting to the image and imu topics.
